baseURL = "https://isbrqu.github.io/cpem55"
languageCode = "es"
title = "CPEM 55"
theme = "hugo-geekdoc"
defaultContentLanguage = "es"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true

disablePathToLower = true
enableGitInfo=true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

[params]
  geekdocLogo = "logo.png"

